apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-proxy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PoojaSharma2410/ICA-2.git
    path: nginx
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-proxy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
