apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  destination:
    namespace: wordpress
    server: 'https://kubernetes.default.svc'
  source:
    path: wordpress
    repoURL: 'https://github.com/PoojaSharma2410/ICA-2.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
